spring:
  datasource:
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iq
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      platform: postgres

server:
  port: 8083